### ISSUE TITLE
node crowd_fund_demo.js ....  Error: Cannot find module 'hfc'

### ISSUE THREAD

**Issue by djc2k** [angrbrd/hyperledger-fabric-basics#4]
When executing the node crowd_fund_demo.js ... command, got the following error:

Error: Cannot find module 'hfc'

**Comment by bancey** [comment]
`npm install` <- should fix that

**Comment by alwillis** [comment]
No luck: here's the output of attempting to install `hfc` after updating `npm`: [https://gist.github.com/alwillis/e9a319ea195f01936197225ffaa6402b](https://gist.github.com/alwillis/e9a319ea195f01936197225ffaa6402b)

**Comment by raderio** [comment]
After 'npm install hfc' I got same about: express, body-parser, debug.

**Comment by bennythejudge** [comment]
I am having this same problem, hfc is not found and `npm install hfc` is failing.
Any help out there?

```
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-08-23T22_21_54_935Z-debug.log
```


```
node crowd_fund_demo.js 192.168.99.100 single-peer
module.js:472
    throw err;
    ^

Error: Cannot find module 'hfc'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/Desktop/workspace/hyperledger-fabric-basics/crowd_fund_demo.js:2:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by gamebusterz** [comment]
@raderio  Just install [this](https://www.npmjs.com/package/npm-install-missing) npm package, and then run it from the project directory, it will download all missing dependecies.

**Comment by bancey** [comment]
@raderio running just `npm install` with no package name after will fetch all of the packages listed in package.json. Since as you ran `npm install hfc` only that specific package was installed.
