### ISSUE TITLE
Issue with line 79 of crowd_fund_demo.js

### ISSUE THREAD

**Issue by anonymousgroundhog** [angrbrd/hyperledger-fabric-basics#5]
I recently found that there is a issue with line 79 of your code in the crowd_fund_demo.js file.
It mentions the following: 
Docker Host IP: 192.168.99.100

Setting keyValStore location to: /temp/keyValStore
Setting membersrvc address to: grpc://192.168.99.100:7054
Adding peer address: grpc://192.168.99.100:7051
Adding peer address: grpc://192.168.99.100:8051
Adding peer address: grpc://192.168.99.100:9051
Adding peer address: grpc://192.168.99.100:10051
Setting eventHubAddr address to: grpc://192.168.99.100:7053

C:\Users\Sean\hyperledger-fabric-basics\crowd_fund_demo.js:79
chain.eventHubConnect(SDK_EVENTHUB_ADDRESS);
      ^

TypeError: chain.eventHubConnect is not a function
    at Object.<anonymous> (C:\Users\Sean\hyperledger-fabric-basics\crowd_fund_demo.js:79:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

I hope this is descriptive enough.

Thanks.

**Comment by vvallabb** [comment]
Getting the same error.. I am running on MAC OS X 10.12.5

update1:

Managed to fix it..
1. Restarted Docker
2. node crowd_fund_demo.js **localhost** single-peer

trick for me was to use 'localhost'

**Comment by anonymousgroundhog** [comment]
I actually tried both and received the same error which is strange. Thanks though for the information vvallabb.

Also note: I am using a Windows 10 system as well to implement this.

**Comment by vvallabb** [comment]
How about trying deleting the file(s) under /tmp/keyValStore?
`rm /tmp/keyValStore/member.admin`
then 
`docker-compose -f single-peer-ca.yaml down`
and then
`docker-compose -f single-peer-ca.yaml up`
This worked for me..

**Comment by anonymousgroundhog** [comment]
There doesn't seem to be anything in the temp folder either. This seems to be quite a strange problem.
Thank you for the try though vvallabb.
